### ISSUE TITLE
enable job distribution across clusters

### ISSUE THREAD

**Issue by bluegenes** [dib-lab/charcoal#16]
If running from a python wrapper around the snakefile, here's an approach:

1. build a `configfile` in the wrapper; write out to file
2. execute snakemake via subprocess, passing in this `configfile` (https://github.com/dib-lab/dammit/blob/add_busco_config/dammit/components/run.py#L168-L186). 
Note: this is nearly identical to method used in `elvers`, with the exception that launching snakemake via the  python api did not submit cluster jobs properly (https://github.com/dib-lab/elvers/blob/master/elvers/__main__.py#L328-L371)

This solution merely enables cluster submission to work properly. To execute, need to provide a profile or cluster-config file to the `snakemake` subprocess command when it's running. @taylorreiter  pointed out that Atlas has a simple method for generating a profile  _for_ the user that only requires minimal user modification https://github.com/metagenome-atlas/clusterprofile. This looks general enough to use directly, or with minimal modification.

If using a wrapper around snakemake, could enable user to pass in their cluster-config info (e.g. `partition: bmm` to the wrapper, and write out a cluster-config prior to execution - no user cluster-config modification would be required. If no cluster information provided, run snakemake as if single node (`--cores/--jobs` both map to the same parameter, and thus are interchangeable).

**Comment by taylorreiter** [comment]
And here's the user documentation for how to use a cluster config with atlas: https://metagenome-atlas.readthedocs.io/en/latest/usage/cluster.html

**Comment by bluegenes** [comment]
Oh right - it's cookiecutter, so you specify the cluster info when you download it, don't need to do this every time! Maybe instead of providing arguments for the cluster params, charcoal could just wrap the cookiecutter command into, e.g. `charcoal cookiecutter`, so user doesn't need to find link.

But, if you want to modify cluster partition for rules (e.g. this is longrunning and can't restart - I want `bmm`, not `bml`), you need to directly modify the `cluster-config.yaml`. Not sure if there's any reason to try to get around that.

**Comment by taylorreiter** [comment]
Yes i love the idea of `charcoal cookiecutter`!

I didn't hate modifying `cluster-config.yml`, but it was a little hard for me to find. Better documentation would have made me feel al little better about the process. Since modifying will be cluster-specific, I don't think there's a big need to make charcoal work around that on its own as long as we provide good documentation around it.

**Comment by ctb** [comment]
Looks like atlas uses basically the same code as dammit --

https://github.com/metagenome-atlas/atlas/blob/master/atlas/atlas.py#L130

**Comment by ctb** [comment]
At the moment I'm leaning towards cluster execution as being unnecessary, though. charcoal is fast enough and lightweight enough that it's better run on a single machine with multiple processes (i.e. with `-j`).

**Comment by ctb** [comment]
(that's not to say that we shouldn't permit it, as it looks straightforward enough to do.)

**Comment by ctb** [comment]
in #44, `charcoal run` works properly on clusters. 🎉

**Comment by ctb** [comment]
cookiecutter bits transferred to #62; the rest seems to work (discussed in documentation)
