### ISSUE TITLE
Demo fails due to missing rule exception in Snakemake

### ISSUE THREAD

**Issue by edgraham** [dib-lab/charcoal#168]
I saw @ctb talk about this program and finally got around to trying it! I installed charcoal per the instructions provided on your quick start page. The install went through seamlessly but when I began running the demo to ensure everything was installed properly I ran into one small issue which seems to be a missing rule in the snakemake Snakefile (albeit I am a snakemake novice so could be wrong) to correspond with the 'clean' part of the demo. The initial demo charcoal run and report worked great and landed me with an output directory that looks like this:

> $ (charcoal) ls output.demo/
> report  stage1  stage1_genome_summary.csv  stage1_hitlist.csv  stage2  stage2_summary.csv

Following those I ran this line to produce cleaned genomes from the output. 

`python -m charcoal run demo/demo.conf -j 4 clean
`
When I did I got this error:

> ** read 2 provided lineages
> ** config file checks PASSED!
> ** from here on out, it's all snakemake...
> Building DAG of jobs...
> MissingRuleException:
> No rule to produce clean (if you use input functions make sure that they don't raise unexpected exceptions).
> Error in snakemake invocation: Command '['snakemake', '-s', '/home/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '-j', '4', 'clean', '--configfile', '/home/charcoal/charcoal/conf/defaults.conf', '/home/charcoal/charcoal/conf/system.conf', 'demo/demo.conf']' returned non-zero exit status 1.

But when I run things myself in python using the charcoal.clean_genome module on the output of the initial charcoal run I end up getting everything to work and output the cleaned/dirty contig files:

> `python -m charcoal.clean_genome --genome ../demo/genomes/LoombaR_2017__SID1050_bax__bin.11.fa.gz --hit-list stage1/LoombaR_2017__SID1050_bax__bin.11.fa.gz.hitlist_for_filtering.csv --contigs-json stage1/LoombaR_2017__SID1050_bax__bin.11.fa.gz.contigs-tax.json --clean LoombaR_2017__SID1050_bax__bin.11.cleaned.fa.gz --dirty LoombaR_2017__SID1050_bax__bin.11.dirty.fa.gz`

**Comment by taylorreiter** [comment]
fixed by #170
