### ISSUE TITLE
distribution, installation and execution options - notes

### ISSUE THREAD

**Issue by ctb** [dib-lab/charcoal#27]
Dist options (may not be mutually exclusive :)

* template repo - complicated for beginners, but is snakemake [recommended approach](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html)
* elvers/spacegraphcats style
  - "app as workflow"
  - conda installable
  - may run into elvers problems (but see atlas, https://metagenome-atlas.readthedocs.io/en/latest/usage/cluster.html) and #16 
  - charcoal config --generate or something
* fully specified path style (--configfile /path/to/config.yaml --snakefile /path/to/Snakefile)
  - need to get PYTHONPATH right;
    `PYTHONPATH=~/dev/charcoal snakemake --snakefile ~/dev/charcoal/Snakefile 
               --configfile test-data/conf-test.yml`
  works.
  - provide your own config file
  - make sure charcoal is installed
  - provide a way for charcoal to give you snakefile? e.g. `$(charcoal snakefile)`. this makes it conda installable...

**Comment by taylorreiter** [comment]
+1000000 for conda installable!

**Comment by ctb** [comment]
#44 makes this "elvers/atlas" style
