### ISSUE TITLE
Unsure what stdout messages mean

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#4]
I just reran the pipeline as specified in [conf/ibd.conf](https://github.com/dib-lab/charcoal/blob/master/conf/ibd.conf), and for the majority of signatures, I saw an output that looked something like this:

```
1370 contigs / 8531608 bp, 603 hash values (missing 764 contigs / 4026787 bp)
```

Is this something I should be concerned about, or just a normal part of the pipeline?

**Comment by ctb** [comment]
this is normal output. the missed contigs has to do with the scaled=10000
value, which has to match the LCA database, and so is quite high at the
moment.

**Comment by taylorreiter** [comment]
wonderful, thank you!
