### ISSUE TITLE
does charcoal need to be run in the charcoal directory?

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#90]
I installed charcoal according to the readme. When I run it in the cloned github directory, it works! When I run it in a different directory, it starts running and then on `rule contigs_clean_just_taxonomy` I get the error message:

```
Activating conda environment: /home/tereiter/github/2020-charcoal-paper/.snakemake/conda/f2fa0ad7
/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/f2fa0ad7/bin/python: Error while finding module specification for 'charcoal.just_taxonomy' (ModuleNotFoundError: No module named 'charcoal')
```

The environment file `.snakemake/conda/f2fa0ad7.yaml` looks like this:
(e.g. the same as https://github.com/dib-lab/charcoal/blob/master/charcoal/conf/env-sourmash.yml)
```
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.6
    - sourmash>=3.3,<4
    - pytest
    - pip
    - pip:
      - dendropy==4.4.0
```

**Comment by ctb** [comment]
see https://github.com/dib-lab/charcoal/issues/45 - tl;dr do `--no-use-conda` for now.

and https://github.com/dib-lab/charcoal/issues/57 is relevant.

**Comment by ctb** [comment]
(pls confirm that works & close issue, or ask more questions :)

**Comment by taylorreiter** [comment]
ah ok! this worked in one env, and royally borked a different one.

The original error in the borked one was `no module named screed`, so I ran `conda install sourmash`, and then got another error about a bad python 3.8 interpreter. I assume that environment just got messed up, and that if I start afresh it would work in this one too. Thank you, closing!

**Comment by ctb** [comment]
excellent!
