### ISSUE TITLE
gzip: GUT_GENOME232182.fa.clean.fa.gz: invalid compressed data--format violated

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/charcoal#92]
One of the clean files output by charcoal is an invalid compressed format. I've re-run charcoal many times with different numbers of threads, and this always produces the same result. 

I'm running charcoal with this snakefile: https://github.com/taylorreiter/2020-charcoal-paper/blob/master/compare.snakefile

The ftp for the culprit genome is: ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/human-gut/v1.0/all_genomes/MGYG-HGUT-033/MGYG-HGUT-03390/genomes1/GUT_GENOME232182.gff.gz

Using zcat begins decompression, but it's terminated when it reaches the line with the invalid format

**Comment by ctb** [comment]
On Fri, May 22, 2020 at 04:06:30PM -0700, Taylor Reiter wrote:
> One of the clean files output by charcoal is an invalid compressed format. I've re-run charcoal many times with different numbers of threads, and this always produces the same result. 
> 
> I'm running charcoal with this snakefile: https://github.com/taylorreiter/2020-charcoal-paper/blob/master/compare.snakefile
> 
> The ftp for the culprit genome is: ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/human-gut/v1.0/all_genomes/MGYG-HGUT-033/MGYG-HGUT-03390/genomes1/GUT_GENOME232182.gff.gz
> 
> Using zcat begins decompression, but it's terminated when it reaches the line with the invalid format

I could hunt this down, I 'spose, but - what's the config file you're using
with charcoal?

also that looks like a GFF file not a genome?

**Comment by taylorreiter** [comment]
Yes it starts out as a GFF file, but the first rule after downloading converts the file to a fasta:
```

rule unembed_gff_fasta:
    input: "inputs/mgnify_genomes/human-gut/v1.0/{genome}.gff3.gz"
    output: "outputs/mgnify_genomes/human-gut/v1.0/{genome}.fa"
    shell:"""
    zcat {input} | awk 'BEGIN {{ doprint = 0}}; \
                        doprint == 1 {{ print $0 }}; \
                        $0 ~ /#FASTA/ {{ doprint = 1 }}' > {output}
    """
```

The conf file looks like this: 

```
# check and validate config settings strictly.
strict: 1

# list of genome filenames to decontaminate
genome_list: inputs/charcoal_conf/mgnify_genome_list.txt
# (optional) list of lineages for input genomes. comment out or leave
# blank if none.
provided_lineages:

# directory in which genome filenames live
genome_dir: outputs/mgnify_genomes/human-gut/v1.0

# location for all generated files
output_dir: 'outputs/charcoal/'

# sourmash query databases for contamination (SBTs, LCAs, or signatures)
gather_db:
 - /home/ctbrown/sourmash_databases/gtdb/build/gtdb-release89-k31.sbt.zip

# lineages CSV (see `sourmash lca index`) for signatures in query databases
lineages_csv: /home/ctbrown/sourmash_databases/gtdb/gtdb-lineages.csv

# scaled and ksize at which to construct genome/contig signatures.
# these should match query databases.
scaled: 1000
ksize: 31
```

it lives here: `/home/tereiter/github/2020-charcoal-paper/inputs/charcoal_conf/mgnify_genomes.conf`

**Comment by taylorreiter** [comment]
(the gff files has the fasta embedded in it after the annotations and demarcated by `##FASTA`)

**Comment by ctb** [comment]
I do see:

% gunzip -c GUT_GENOME232182.fa.clean.fa.gz > out

gzip: GUT_GENOME232182.fa.clean.fa.gz: invalid compressed data--format violated

what's the output of charcoal run if you delete just that file and ask
charcoal to recreate?

--t

**Comment by taylorreiter** [comment]
Annoyingly, the way i have this rule written, my snakemake pipeline thinks that one missing *clean.fa.gz file means that all specified outputs from the rule need to be removed and regenerated. Luckily i haven't put any of the gather files as outputs, so it only regenerates the *clean.fa.gz etc. files. But it does re-run all of them.

**Comment by taylorreiter** [comment]
(I was trying to brainstorm a way to run charcoal on a single file instead having to create a list of files from a dir. I think this would be helpful when scaling this up to ~thousands of genomes; I could create the summary output file in a separate rule myself.)

**Comment by ctb** [comment]
On Fri, May 22, 2020 at 04:58:48PM -0700, Taylor Reiter wrote:
> (I was trying to brainstorm a way to run charcoal on a single file instead having to create a list of files from a dir. I think this would be helpful when scaling this up to ~thousands of genomes; I could create the summary output file in a separate rule myself.)

can you try:

charcoal run <config file> <desired output file>

?

thx,
--t

**Comment by taylorreiter** [comment]
What is `<desired output file>`?

`GUT_GENOME232182.fa.clean.fa.gz`?

**Comment by taylorreiter** [comment]
Because that gives me:
```
$ charcoal run inputs/charcoal_conf/mgnify_genomes.conf GUT_GENOME232182.fa.clean.fa.gz
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
MissingRuleException:
No rule to produce GUT_GENOME232182.fa.clean.fa.gz (if you use input functions make sure that they don't raise unexpected exceptions).
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/Snakefile', '--use-conda', '-j', '1', 'GUT_GENOME232182.fa.clean.fa.gz', '--configfile', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/conf/defaults.conf', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/conf/system.conf', 'inputs/charcoal_conf/mgnify_genomes.conf']' returned non-zero exit status 1.
```

**Comment by taylorreiter** [comment]
And dry run says there is nothing to be done
```
$ charcoal run inputs/charcoal_conf/mgnify_genomes.conf -n
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
Nothing to be done.
```

**Comment by ctb** [comment]
(give it the full path to the desired output file)

**Comment by taylorreiter** [comment]
oh my...yup.

```
$ charcoal run inputs/charcoal_conf/mgnify_genomes.conf outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz
outputs/charcoal/GUT_GENOME232182.fa.dirty.fa.gz
outputs/charcoal/GUT_GENOME232182.fa.report.txt
outputs/charcoal/GUT_GENOME232182.fa.contigs.csv
outputs/charcoal/GUT_GENOME232182.fa.summary.csv
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/Snakefile', '--use-conda', '-j', '1', 'outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz', '--configfile', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/conf/defaults.conf', '/home/tereiter/github/2020-charcoal-paper/.snakemake/conda/1f582d50/lib/python3.7/site-packages/charcoal/conf/system.conf', 'inputs/charcoal_conf/mgnify_genomes.conf']' returned non-zero exit status 1.
```

**Comment by ctb** [comment]
On Fri, May 22, 2020 at 05:15:43PM -0700, Taylor Reiter wrote:
> oh my...yup.

protip: you can put any snakemake arguments you want after the config file :).
so,

carcoal run inputs/charcoal_conf/mgnify_genomes.conf --cleanup-metadata outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz

should work

**Comment by taylorreiter** [comment]
```
charcoal run inputs/charcoal_conf/mgnify_genomes.conf --no-use-conda outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz --rerun-incomplete
```

Ended up working. I'm not sure why snakemake didn't catch that without the flag, but I'll just add `--rerun-incomplete` defacto from now on.

Sorry & thank you!

**Comment by ctb** [comment]
On Fri, May 22, 2020 at 05:30:33PM -0700, Taylor Reiter wrote:
> ```
> charcoal run inputs/charcoal_conf/mgnify_genomes.conf --no-use-conda outputs/charcoal/GUT_GENOME232182.fa.clean.fa.gz --rerun-incomplete
> ```
> 
> Ended up working. I'm not sure why snakemake didn't catch that without the flag, but I'll just add `--rerun-incomplete` defacto from now on.
> 
> Sorry & thank you!

np!
